from fastapi import HTTPException, UploadFile
from qwen.qwen import qwen_file

async def verify_id_card(file : UploadFile):
  system = """
  You are an expert Identity Verification (IDV) assistant. Your task is to analyze an image of a person holding an identification card to verify authenticity and identity match.

  Follow these analytical steps:
  1. **Document Identification:** Determine the country of origin and the specific type of ID (e.g., Passport, Driver's License, National ID).
  2. **Face Match Analysis:** Compare the physical features of the person holding the card with the photo printed on the ID. Look at bone structure, eye shape, and facial proportions. Account for age differences or lighting.
  3. **Liveness & Integrity Check:** Look for signs of "digital spoofing" (e.g., a person holding a tablet showing a photo) or physical tampering (e.g., a photo pasted over the original ID).
  4. **Data Extraction:** Extract the Name and ID Number if clearly legible.

  Provide your final verdict as: MATCH, MISMATCH, or INCONCLUSIVE (if the image is too blurry).
  """

  prompt = """
  Please analyze the attached image for identity verification. 

  **Tasks:**
  1. **Identify the Document:** Which country issued this ID and what type of document is it?
  2. **Face Comparison:** Does the person holding the card match the photo on the card? Provide a brief reasoning for your conclusion.
  3. **Validity Check:** Check for security features (holograms, clear fonts, official seals) and ensure the card doesn't look like a printed paper copy or a digital screen.
  4. **Legibility:** Is the text on the card clear enough to read? 
  5. **AI detection:** Assess if the image might be AI-generated or digitally manipulated.

  **Output Format:**
  - **Generated By AI:** [YES / NO / UNCLEAR]
  - **Country/Type:** [e.g., France / National ID]
  - **Verification Result:** [MATCH / MISMATCH / INCONCLUSIVE]
  - **Confidence Score:** [0-100%]
  - **Reasoning:** [Brief explanation of your findings]
  """

  result = await qwen_file(prompt, system, file)

  return result
